# Quality Control Orders (QCO) Knowledge Repository
from typing import List, Dict, Any

SEED_QCOS: List[Dict[str, Any]] = [
    {
        "qco_number": "S.O. 3968(E)",
        "title": "Domestic Pressure Cooker (Quality Control) Order, 2020",
        "product_name": "Domestic Pressure Cooker",
        "is_number": "IS 2347:2017",
        "ministry": "Ministry of Commerce and Industry (Department for Promotion of Industry and Internal Trade - DPIIT)",
        "notification_date": "2020-10-21",
        "enforcement_date": "2021-02-01",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Pressure_Cooker_QCO_2020.pdf",
        "notes": "Prohibits manufacture, import, sale, distribution or storage of domestic pressure cookers unless they conform to IS 2347:2017 and bear the Standard Mark (ISI mark) under a license from the Bureau of Indian Standards as per Scheme-I of Schedule-II of BIS (Conformity Assessment) Regulations, 2018.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 3943(E)",
        "title": "Toys (Quality Control) Order, 2020",
        "product_name": "Toys and Playthings",
        "is_number": "IS 9873 (Part 1):2019",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "notification_date": "2020-02-25",
        "enforcement_date": "2021-01-01",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Toys_QCO_2020.pdf",
        "notes": "Makes ISI mark under Scheme-I mandatory for all non-electric and electric toys sold or imported into India.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 2884(E)",
        "title": "Electrical Appliances (Quality Control) Order, 2023",
        "product_name": "Electric Iron",
        "is_number": "IS 302-2-3:2021",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "notification_date": "2023-06-20",
        "enforcement_date": "2024-01-01",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Electrical_Appliances_QCO_2023.pdf",
        "notes": "Mandates BIS certification under Scheme-I for electric irons and domestic heating appliances.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 1195(E)",
        "title": "Plugs and Socket-Outlets (Quality Control) Order, 2021",
        "product_name": "Plugs and Socket-Outlets",
        "is_number": "IS 1293:2019",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "notification_date": "2021-03-12",
        "enforcement_date": "2021-12-01",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Plugs_Sockets_QCO_2021.pdf",
        "notes": "Mandatory ISI mark required for 6A and 16A domestic plugs and sockets.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 4390(E)",
        "title": "Cables and Wires (Quality Control) Order, 2023",
        "product_name": "PVC Insulated Cables",
        "is_number": "IS 694:2010",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "notification_date": "2023-10-05",
        "enforcement_date": "2024-04-01",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Cables_QCO_2023.pdf",
        "notes": "Mandatory ISI certification for low voltage PVC cables up to 1100V.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 1729(E)",
        "title": "Insulating Mats for Electrical Purposes (Quality Control) Order, 2024",
        "product_name": "Insulating Mats for Switchboards",
        "is_number": "IS 15652:2006",
        "ministry": "Ministry of Power",
        "notification_date": "2024-02-15",
        "enforcement_date": "2024-08-15",
        "status": "Mandatory",
        "source_url": "https://powermin.gov.in/qco_insulating_mats.pdf",
        "notes": "Mandates ISI mark for safety insulating mats used in high-voltage industrial substations.",
        "is_demo": False,
    },
    {
        "qco_number": "G.S.R. 760(E)",
        "title": "Packaged Drinking Water (Prohibition and Restriction on Sales) Order, 2001",
        "product_name": "Packaged Drinking Water",
        "is_number": "IS 14543:2018",
        "ministry": "Ministry of Consumer Affairs, Food and Public Distribution",
        "notification_date": "2001-03-29",
        "enforcement_date": "2001-09-29",
        "status": "Mandatory",
        "source_url": "https://consumeraffairs.nic.in/qco_packaged_water.pdf",
        "notes": "Mandatory ISI Certification mark under Scheme-I for all packaged drinking water manufacturing and sale in India.",
        "is_demo": False,
    },
    {
        "qco_number": "S.O. 1822(E)",
        "title": "Electric Water Heaters (Quality Control) Order, 2023",
        "product_name": "Electric Storage Water Heaters",
        "is_number": "IS 2082:2018",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "notification_date": "2023-05-18",
        "enforcement_date": "2023-11-18",
        "status": "Mandatory",
        "source_url": "https://dpiit.gov.in/sites/default/files/Water_Heater_QCO_2023.pdf",
        "notes": "Mandatory ISI mark under Scheme-I for stationary storage electric water heaters (geysers).",
        "is_demo": False,
    }
]
